### ISSUE TITLE
I love Nodejs

### ISSUE THREAD

**Issue by slashtu** [nodeschool/taiwan#2]
大家好, 我叫 Slash. 目前工作是 POS Solution 相關產業. 用 Javascript 寫 POS Web App.
工作上比較常接觸的有 Linux, Grunt, Coffeescript, Git.

[這是我用 Nodejs 架的網站 Slash's Life](http://slash.tw/life)

因為對 Nodejs 有興趣, 也讀過一些文件
希望可以幫忙並且更進步了解 Nodejs. 請多多指教 謝謝.

**Comment by slashtu** [comment]
補上 [facebook](https://www.facebook.com/slashtu)

**Comment by cfsghost** [comment]
已發送邀請，我們會盡快找個時間來討論分工。:-)

**Comment by slashtu** [comment]
got it, thx.
