### ISSUE TITLE
自介

### ISSUE THREAD

**Issue by azole** [nodeschool/taiwan#3]
大家好，我是 azole，朋友都叫我小賴。

做過網站前後端(當年沒有這樣分)、socket server/client、視窗程式、編譯器...等，現在用 nodejs 開發 xmpp。接觸過的各式語言中，最喜歡 js，希望能有機會參與推廣 nodejs，但因為公司地點非常的遙遠，回到市中心的時候都不早了，不曉得能以怎麼樣的方式來參與。

這是我的fb: https://www.facebook.com/azoleLai

**Comment by cfsghost** [comment]
It's ok.

已送出加入邀請，我們可以在假日辦活動也不是問題。:-)
