### ISSUE TITLE
Nodeschool Taiwan Workshop Kickoff Party! (10/13)

### ISSUE THREAD

**Issue by cfsghost** [nodeschool/taiwan#5]
### 強力放送！緊急加開！Nodeschool Workshop！

相信大家對 JSDC 2014 仍意猶未盡，在星期四的 Node.js Party 裡，也直接感受到外國講者們對於 JavaScript 和 Node.js 強大的熱情。尤其是看到他們各自維護了數百個 NPM 模組，以及五分鐘寫一個有趣且結構完整的 NPM 模組，你是否被激勵到開始動手自幹起自己的模組了呢？

趁著講者們尚未離開台灣，我們臨時起意，將緊接著在星期一（10/13）晚上七點，於摩茲工寮加開一場 Nodeschool 的 Workshop 活動。無論是想入門的初學者、以及想學進階技術的高手們，都擁躍報名歡迎參加！

---

We'd like to make an announcement for Nodeshool Taiwan before foreign mentor leaves. It means  unplanned Nodeschool Taiwan Workshop will take place on October 13 at 19:00. Welcome to join us!

**Comment by fengmk2** [comment]
能給一個google map link嗎？

**Comment by horsekitlin** [comment]
請問這場會有錄影紀錄嘛？
可否造福一下無法跟上的中南部山豬群們！！！！

**Comment by fantasywind** [comment]
Map:

https://goo.gl/maps/YynBg

**Comment by webber0928** [comment]
好讓人興奮噢～

**Comment by fengmk2** [comment]
我看報名已滿，是否還能參加？
2014-10-13 上午11:03于 "Chia Yu Pai" notifications@github.com写道：

**Comment by cfsghost** [comment]
這次有點臨時，我們會看一下能不能錄影。

原本預計是 30 ~ 50 人左右，不過現在 30 人報名已經滿了。（我沒說沒報到的人可不可以來，我只怕場地太擠 XD）

**Comment by cfsghost** [comment]
最新消息，場地已經談妥。已加開名額！快來報名！

http://nodeschool.kktix.cc/events/867150f7
