### ISSUE TITLE
自我介紹

### ISSUE THREAD

**Issue by onlinemad** [nodeschool/taiwan#6]
Hello, 我是 Ian

目前是頑皮工坊的 backend engineer 

公司所有的 backend 都是 node 

希望可以一起參與推廣 node

這是我的 facebook 

https://www.facebook.com/onlinemad

 請多多指教

謝謝

**Comment by cfsghost** [comment]
歡迎加入！如果有任何推廣活動或工作，我們之後都會在 issue tracker 上做討論！:-)
