### ISSUE TITLE
響應 5/23 NodeSchool International Day

### ISSUE THREAD

**Issue by cfsghost** [nodeschool/taiwan#8]
![NodeSchool International Day](http://nodeschool.io/international-day/images/international-day-logo.png)
# 活動目標

NodeSchool 將 5/23 定為全球性的 International Day，台灣地區身為全球技術社群的一份子，理所當然要響應辦一場 NodeScool 活動！

這個活動的目的，是為了讓更多人來學習 Node.js/io.js、JavaScript 和 WebGL 等技術。透過 NodeSchool 的各式教材文獻，除了可以自學之外，亦可以與參加活動的朋友一起討論交流。不只是初學者，已經相當有實力的朋友也可以前來一起學習更多新技術。
## 活動內容

核心基礎課程
1. Git and Github 入門
2. JavaScript 入門
3. Node.js 入門
4. How to use NPM

進階課程
1. Promise
2. Express
3. 任何 NodeSchool 上有列出的課程
## 活動人數

150 人
## 活動時間

2015 年 5 月 23 日 10:00 至 18:00
## 活動需求

我們需要一些事前準備，讓活動可以順利舉行。
### 指導員人力

因為這個活動會有初學者來參加，所以會需要一些指導員在現場幫忙引導。指導員主要工作是當有人（通常是初學者）在進行 NodeScool 的教材時若遭遇到了問題，可以協助排除問題。

我們理解，NodeSchool 有非常多的課程教材，涉及非常多種技術，要熟悉全部領域相當困難，所以，除了具有 Node.js、JavaScript 經驗的指導員之外，若有人熟任何一樣技術，願意在活動上幫忙當指導員，麻煩也務必幫忙，並在此留下您的資訊！

課程教材的項目可參考：
http://nodeschool.io/

有意願當指導員的朋友，請麻煩於討論串後留下資訊：

名字（或網路上稱呼）：HeyMan
email：_hey@example.com_
能協助的技術：_Node.js_、_JavaScript_、_WebGL_
### 食物

我們需要一些食物和餐點，大家可各自攜帶點心食物前來分享。本次社群活動，將共同分攤餐飲、場地租借及清潔費用，所以會向參加者酌收 400 元。
### 場地

台北市大同區承德路三段 232 號 B1 
(圓山捷運站 2 號出口出來後，延著庫倫街步行 2 分鐘到承德路，到對面橡木桶洋酒旁，即可抵達。) 
![場地照片](http://i.imgur.com/iL1n11W.jpg?1)
註：這是 Hackathon Taiwan 辦活動的同一個場地。
### 報名頁面

http://nodeschool.kktix.cc/events/867150f7-0ae723

**Comment by dca** [comment]
先填坑

名字（或網路上稱呼）：Dca
email：dcahsu@gmai.com
能協助的技術：Node.js、JavaScript、端茶水

**Comment by wwwy3y3** [comment]
填坑+1

名字（或網路上稱呼）：wwwy3y3
email：wwwy3y3@gmail.com
能協助的技術：Node.js, express, promise, 爽朗的微笑

**Comment by azole** [comment]
名字（或網路上稱呼）：azole
email：_azolelai@gmail.com azolelai@gmail.com_
能協助的技術：_Node.js_、_JavaScript_

Fred Chien notifications@github.com 於 2015年5月11日 上午12:38 寫道：

**Comment by chochinlu** [comment]
名字: 卓青
能協助的技術：_Node.js_、_JavaScript_

azole notifications@github.com 於 2015年5月11日 上午9:29 寫道：

**Comment by andrewchen30** [comment]
想幫忙
名字（或網路上稱呼）：AndrewChen
email：chenpoanandrew@gmail.com
能協助的技術：Node.js, express

**Comment by kaichiachen** [comment]
能幫忙簡單的事務~~
名字:鍇嘉
email: singbird81@gmail.com
能協助的技術：javascript、基本的Node.js、Restful的express

**Comment by zorro0555** [comment]
名字：Zorro
email：zorro0555@gmail.com
能協助的技術：JavaScript

**Comment by teke15** [comment]
名子：Ocean Lin 林國祥
email：teke15@gmail.com
能協助的技術：JavaScript

**Comment by DJFeu** [comment]
名字：Adam Hung 洪立剛
email：magic.music@gmail.com
能協助的技術：JavaScript 從0速學 簡報

**Comment by wazho** [comment]
名字：Salmon
email：salmon.zh.tw@gmail.com
能協助的技術：Node.js, Async, Express, Full-stack

**Comment by hong19** [comment]
名字：Hong 陳致宏
email: jimmy600kimo@hotmail.com
能協助的技術: JavaScript

**Comment by cfsghost** [comment]
各位大大，活動開放報名囉！麻煩報一下吧！

http://nodeschool.kktix.cc/events/867150f7-0ae723

另外，也許我們可以在下星期約某一天晚上，討論一下活動的內容的進行？

**Comment by hong19** [comment]
Sorry， 住台中，有點不方便參與討論
有線上會議這個選項嗎？

**Comment by wazho** [comment]
@cfsghost 請問 Fred 前輩，是哪一天的晚上呢？ :)

**Comment by cfsghost** [comment]
是 5/23 (六) 早上 10:00 ~ 18:00。:-)

**Comment by wazho** [comment]
Sorry，我沒說清楚。

我是對 Fred 前輩前幾則回覆「另外，也許我們可以在下星期約某一天晚上，討論一下活動的內容的進行？」，這一句做提問 @@"

**Comment by alvinsj** [comment]
名字：Alvin Ng
email：email.to.alvin@gmail.com
能協助的技術：Javascript

**Comment by cfsghost** [comment]
感謝各位！

如果有空的人，我們目前暫定本週四（5/21）晚上七點，在 Node.js Party 先見面討論吧！

聚會地點：卡市達創業加油站
台北市大安區安和路二段23巷11號1樓
(捷運信義安和站3.4號出口，沿通安街第二路口右轉) 

地圖：https://goo.gl/O8nDPS

**Comment by dca** [comment]
這週我們還有讀書會可以亂入 [小聲]

**Comment by teke15** [comment]
請問開會時間？幾點呢？

2015-05-20 12:06 GMT+08:00 Dca notifications@github.com:

> 這週我們還有讀書會可以亂入 [小聲]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/taiwan/issues/8#issuecomment-103748994.

## 

請上網搜尋 Fasobook http://www.fasobook.com.tw

**Comment by cfsghost** [comment]
本週四（5/21）晚上七點。

**Comment by SimonSun1988** [comment]
暱稱: Simon
專長: 洗洗睡

上面每位都是大大
